package com.musicabinet.mobile

/**
 * @author Kirchhoff-
 */

object Constants {
    const val GUIDE_MACHINE_REQUEST_CODE = 12000
    const val GUIDE_MACHINE_ELEMENT_ARG = "GUIDE_MACHINE_ELEMENT_ARG"
    const val GUIDE_MACHINE_TONE_CODE_ARG = "GUIDE_MACHINE_TONE_CODE_ARG"
    const val GUIDE_MACHINE_CHORD_CODE_ARG = "GUIDE_MACHINE_CHORD_CODE_ARG"
    const val GUIDE_MACHINE_ELEMENT_RESULT_ARG = "GUIDE_MACHINE_ELEMENT_RESULT_ARG"
    const val GUIDE_MACHINE_TAG_RESULT_ARG = "GUIDE_MACHINE_TAG_RESULT_ARG"


    const val NOTE_REQUEST_CODE = 13000
    const val NOTE_TAG_ARG = "NOTE_TAG_ARG"
    const val NOTE_ELEMENT_ARG = "NOTE_ELEMENT_ARG"
    const val NOTE_SELECTED_ELEMENT_ARG = "NOTE_SELECTED_ELEMENT_ARG"
    const val NOTE_SELECTED_MODULE_ID_ARG = "NOTE_SELECTED_MODULE_ID_ARG"
    const val NOTE_SELECTED_COURSE_ID_ARG = "NOTE_SELECTED_COURSE_ID_ARG"
    const val NOTE_RESULT_ARG = "NOTE_RESULT_ARG"
    const val NOTE_MODULE_RESULT_ARG = "NOTE_MODULE_RESULT_ARG"
    const val NOTE_COURSE_RESULT_ARG = "NOTE_COURSE_RESULT_ARG"


    const val IMPROVISATION_FILE_NAME = "improvisation.txt"
}